name: "Terraform Init"
description: "Run Terraform init to initialise your terraform code"

inputs:
  working-directory:
    description: 'Directory containing main.tf'
    required: false
    default: '.'
    type: string
  terraform-version:
    description: 'Terraform version to use'
    required: false
    default: '~1.7.0'
    type: string
  github-environment:
    description: 'The name of your AWS environment. Create an environment secret called ACCOUNT_ID, also.'
    required: false
    default: 'placeholder'
    type: string
  aws-region:
    description: 'AWS Region for the State Bucket and Resources'
    default: eu-west-2
    required: true
    type: string
  state-bucket:
    description: 'Name of the S3 bucket for Terraform State'
    required: true
    type: string
  state-dynamodb-table:
    description: 'Name of the DynamoDB table'
    required: true
    type: string
  role-to-assume:
    description: 'AWS Role name for OIDC'
    required: true
    type: string
  account_id:
    description: "AWS Account ID"
    required: true

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    - uses: aws-actions/configure-aws-credentials@v4
      name: Configure AWS IdP Credentials
      with:
        role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.role-to-assume }}
        role-session-name: GitHubActions
        retry-max-attempts: 5
        aws-region: ${{ inputs.aws-region }}

    - name: Bootstrap Terraform Backend
      id: bootstrap
      shell: bash
      env:
        BUCKET: ${{ inputs.state-bucket }}
        TABLE: ${{ inputs.state-dynamodb-table }}
        REGION: ${{ inputs.aws-region }}
      run: |
        echo "Does S3 bucket and DynamoDB table exist?"

        if aws s3api head-bucket --bucket "$BUCKET" --region "$REGION" 2>/dev/null; then
          echo "S3 Bucket $BUCKET exists."
        else
          echo "S3 Bucket $BUCKET not found. Creating..."
          aws s3api create-bucket --bucket "$BUCKET" --region "$REGION" --create-bucket-configuration LocationConstraint="$REGION"
          aws s3api put-bucket-versioning --bucket "$BUCKET" --versioning-configuration Status=Enabled --region $REGION
          echo "S3 Bucket created and versioning enabled."
        fi

        if aws dynamodb describe-table --table-name "$TABLE" --region "$REGION" >/dev/null 2>&1; then
           echo "DynamoDB Table $TABLE exists."
        else
           echo "DynamoDB Table $TABLE not found. Creating..."
           aws dynamodb create-table \
            --table-name "$TABLE" \
            --attribute-definitions AttributeName=LockID,AttributeType=S \
            --key-schema AttributeName=LockID,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST --region "$REGION"
           echo "DynamoDB Table created."
        fi

    - name: Cache Terraform
      uses: actions/cache@v4
      with:
        path: .terraform
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.state-bucket }}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=${{ inputs.aws-region }}" \
          -backend-config="dynamodb_table=${{ inputs.state-dynamodb-table }}" \
          -input=false
