name: Standard Terraform Pipeline

on:
  workflow_call:
    inputs:
      apply-branch:
        description: "Adds the ability to define which branch you want to be able to apply to"
        required: false
        default: "main"
        type: string
      aws-region:
        description: "AWS Region for the State Bucket and Resources"
        default: eu-west-2
        required: false
        type: string
      github-environment:
        description: "The name of your AWS environment. Create an environment secret called ACCOUNT_ID, also."
        required: false
        default: "placeholder"
        type: string
      role-to-assume:
        description: "AWS Role name for OIDC"
        required: false
        type: string
      state-bucket:
        description: "Name of the S3 bucket for Terraform State"
        required: false
        type: string
      state-dynamodb-table:
        description: "Name of the DynamoDB table"
        required: false
        default: ""
        type: string
      state-key:
        description: "Where you want the state key to be"
        required: false
        type: string
        default: "terraform.tfstate"
      terraform-version:
        description: "Terraform version to use"
        required: false
        default: "~1.7.0"
        type: string
      tfvars-file:
        required: false
        type: string
        default: ""
      use-backend:
        description: "Whether to use a remote backend for Terraform state"
        required: false
        default: true
        type: boolean
      working-directory:
        description: "Directory containing main.tf"
        required: false
        default: "."
        type: string
    secrets:
      account_id:
        required: false
      sonar_host_url:
        required: false
      sonar_token:
        required: false

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform-standardised-pipeline:
    name: "Terraform Standardised Pipeline"
    runs-on: ubuntu-latest
    environment: ${{ inputs.github-environment }}

    permissions:
      contents: read
      pull-requests: write
      id-token: write

    outputs:
      result: ${{ steps.quality-checks.outcome }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Init
        id: init
        uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/actions/init@main
        with:
          account_id: ${{ secrets.ACCOUNT_ID }}
          aws-region: ${{ inputs.aws-region }}
          github-environment: ${{ inputs.github-environment }}
          role-to-assume: ${{ inputs.role-to-assume }}
          state-bucket: ${{ inputs.state-bucket }}
          state-dynamodb-table: ${{ inputs.state-dynamodb-table }}
          state-key: ${{ inputs.state-key }}
          terraform-version: ${{ inputs.terraform-version }}
          working-directory: ${{ inputs.working-directory }}
          use-backend: ${{ inputs.use-backend }}

      - name: Terraform Fmt
        id: quality-checks
        uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/actions/fmt@main
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Terraform Validate
        if: success() || failure()
        uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/actions/validate@main
        with:
          terraform-version: ${{ inputs.terraform-version }}
          working-directory: ${{ inputs.working-directory }}

      # TODO: TFLint is not part of the official terraform CLI and is more complex. Suggest keeping that in separate repo and pointing to it here, with the ability to disable
      - name: TFLint
        if: success() || failure()
        uses: Home-Office-Digital/core-cloud-workflow-tflint-scan@main

      - name: Terraform Test
        if: success() || failure()
        uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/actions/test@main
        with:
          working-directory: ${{ inputs.working-directory }}
          sonar-host-url: ${{ secrets.sonar_host_url }}
          sonar-token: ${{ secrets.sonar_token }}

      - name: Terraform Plan
        if: ${{ inputs.use-backend == true }}
        id: plan
        uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/actions/plan@main
        with:
          account_id: ${{ secrets.ACCOUNT_ID }}
          aws-region: ${{ inputs.aws-region }}
          github-environment: ${{ inputs.github-environment }}
          role-to-assume: ${{ inputs.role-to-assume }}
          terraform-version: ${{ inputs.terraform-version }}
          tfvars-file: ${{ inputs.tfvars-file }}
          working-directory: ${{ inputs.working-directory }}

      - name: Terraform Apply
        if: ${{ inputs.use-backend == true && github.ref_name == inputs.apply-branch }}
        id: apply
        uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/actions/apply@main
        with:
          apply-branch: ${{ inputs.apply-branch }}
          account_id: ${{ secrets.ACCOUNT_ID }}
          aws-region: ${{ inputs.aws-region }}
          github-environment: ${{ inputs.github-environment }}
          role-to-assume: ${{ inputs.role-to-assume }}
          terraform-version: ${{ inputs.terraform-version }}
          working-directory: ${{ inputs.working-directory }}
